In [1]:
from pathomics_research_utils.data_generators import ClassificationDataGenerator
from pathomics_research_utils.models import AlexNet
from pathomics_research_utils import utils
import numpy as np
import os

In [2]:
#Hyperparams
lr = 1e-3
n_epochs = 5

In [3]:
data_dir = '/home/krypt/myStuff/projects/cancer-research/data/lymphoma_2/'

In [4]:
data_generator = ClassificationDataGenerator(images_dir=data_dir)

In [5]:
model = AlexNet(input_shape=(32,32,3), num_classes=3)

In [6]:
model.compile(optimizer='adam', learning_rate=lr, loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit_generator(
    generator=data_generator,
    epochs=n_epochs
)

Epoch 1/5
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[1. 1. 1.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
0
[1. 1. 1.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
    1/16082 [..............................] - ETA: 3:12:23 - loss: 1.0074 - accuracy: 0.0000e+00
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[1. 1. 1.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0

   16/16082 [..............................] - ETA: 1:56:50 - loss: 0.8361 - accuracy: 0.2812
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
0
[0. 0. 0.]
1
[0. 0. 0.]
1
[1. 1. 1.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
   17/16082 [..............................] - ETA: 1:56:30 - loss: 0.8248 - accuracy: 0.26471
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[1. 1. 1.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 

   32/16082 [..............................] - ETA: 1:54:05 - loss: 0.5443 - accuracy: 0.25101
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[1. 1. 1.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
   33/16082 [..............................] - ETA: 1:54:01 - loss: 0.5336 - accuracy: 0.26422
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[1. 1. 1.]
2
[0. 0. 0.]
2
[0. 0. 0.]
2
[0. 0.

KeyboardInterrupt: 

1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]
1
[0. 0. 0.]


In [ ]:
model.predict(utils.read_image('/home/krypt/myStuff/projects/cancer-research/data/lymphoma_2/MCL//0.tif').astype(np.float64).reshape((1,32,32,3)))